name: delta_peak_app
description: نخستین نسخه اپلیکیشن موبایلی DeltaPeak APP
publish_to: none
version: 0.5.12+21

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  archive: ^3.6.1
  crypto: ^3.0.3
  file_picker: ^8.1.7
  flutter_secure_storage: ^10.3.1
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/peaks.db
    - assets/data_patch_v391_b09.json
    - assets/education_v1.json
